import { ref } from "vue";

export const products = ref([
  {
    name: "Браслет",
    price: 15,
    description: "Стильний браслет із логотипом школи.",
    icon: "game-icons:ring",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Брелок",
    price: 15,
    description: "Маленький брелок для ключів.",
    icon: "iconoir:rings",
    isInWishlist: false,
    inStock: false, // Ще в дорозі
  },
  {
    name: "Наліпки",
    price: 25,
    description: "Набір яскравих наліпок для вашого ноутбука чи блокнота.",
    icon: "ph:sticker-duotone",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Ручка/олівець",
    price: 25,
    description: "Брендована ручка або олівець для успішного навчання.",
    icon: "ph:pencil-duotone",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Зошит",
    price: 30,
    description: "Якісний зошит для нотаток та ідей.",
    icon: "solar:notebook-minimalistic-linear",
    isInWishlist: false,
    inStock: false, // Ще в дорозі
  },
  {
    name: "Значок",
    price: 30,
    description: "Металевий значок із символом вашого курсу.",
    icon: "ph:circle-fill",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Гумки для стирання",
    price: 40,
    description: "Пара гумок для стирання помилок.",
    icon: "vaadin:elastic",
    isInWishlist: false,
    inStock: false, // Ще в дорозі
  },
  {
    name: "Попсокет",
    price: 50,
    description: "Зручний попсокет для телефону.",
    icon: "icon-park-outline:spinning-top",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Підставка під телефон",
    price: 50,
    description: "Зручна підставка для перегляду відео на телефоні.",
    icon: "material-symbols:nest-cam-stand",
    isInWishlist: false,
    inStock: false, // Ще в дорозі
  },
  {
    name: "Шкарпетки",
    price: 100,
    description: "Фірмові шкарпетки Logika. Яскраві та зручні.",
    icon: "ph:sock-duotone",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Пенал",
    price: 100,
    description: "Практичний пенал для зберігання канцелярії.",
    icon: "solar:airbuds-case-bold",
    isInWishlist: false,
    inStock: false, // Ще в дорозі
  },
  {
    name: "Пляшка",
    price: 150,
    description: "Стильна пляшка для води, щоб завжди мати гідратацію.",
    icon: "material-symbols:water-bottle-outline-rounded",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Килимок для мишки",
    price: 180,
    description: "Якісний килимок для мишки з ексклюзивним дизайном.",
    icon: "ph:mouse-duotone",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Бананка",
    price: 220,
    description: "Зручна бананка для найнеобхідніших речей.",
    icon: "game-icons:school-bag",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Футболка",
    price: 250,
    description: "Класична футболка з логотипом школи.",
    icon: "ph:t-shirt-duotone",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Парасолька",
    price: 250,
    description: "Фірмова парасолька для захисту від негоди.",
    icon: "ph:umbrella-duotone",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Навушники",
    price: 300,
    description: "Якісні бездротові навушники для музики та навчання.",
    icon: "ph:headphones-duotone",
    isInWishlist: false,
    inStock: true,
  },
  {
    name: "Музична колонка",
    price: 300,
    description: "Портативна колонка для улюбленої музики.",
    icon: "akar-icons:music-album-fill",
    isInWishlist: false,
    inStock: false, // Ще в дорозі
  },
  {
    name: "Знижка 30% на перший місяць",
    price: 300,
    description: "Приємний бонус для продовження навчання.",
    icon: "ph:percent-duotone",
    isInWishlist: false,
    inStock: true,
  },
]);
